# Generated by Django 5.2.4 on 2025-07-21 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeadachesReported',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_time', models.DateField()),
                ('headache_reported', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='PressureStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_time', models.DateField()),
                ('past_min_24', models.FloatField()),
                ('past_max_24', models.FloatField()),
                ('past_min_3', models.FloatField()),
                ('past_max_3', models.FloatField()),
                ('past_min_7', models.FloatField()),
                ('past_max_7', models.FloatField()),
                ('next_min_24', models.FloatField()),
                ('next_max_24', models.FloatField()),
                ('next_min_3', models.FloatField()),
                ('next_max_3', models.FloatField()),
                ('next_min_7', models.FloatField()),
                ('next_max_7', models.FloatField()),
                ('past_range_24', models.FloatField()),
                ('next_range_24', models.FloatField()),
                ('past_range_3', models.FloatField()),
                ('next_range_3', models.FloatField()),
                ('past_avg_range_3', models.FloatField()),
                ('next_avg_range_3', models.FloatField()),
                ('past_range_7', models.FloatField()),
                ('next_range_7', models.FloatField()),
                ('next_avg_range_7', models.FloatField()),
                ('past_avg_range_7', models.FloatField()),
                ('past_range_30', models.FloatField()),
                ('past_avg_range_30', models.FloatField()),
                ('past_avg_hrly_change_24', models.FloatField()),
                ('next_avg_hrly_change_24', models.FloatField()),
                ('past_avg_hrly_change_3', models.FloatField()),
                ('next_avg_hrly_change_3', models.FloatField()),
                ('past_avg_hrly_change_7', models.FloatField()),
                ('next_avg_hrly_change_7', models.FloatField()),
                ('past_avg_hrly_change_30', models.FloatField()),
            ],
        ),
    ]
